.TH TEMA.SIMULATE 1 local
.SH NAME
tema.simulate \- Simulate model
.SH SYNOPSIS
.B tema.simulate
[ filename ]
.RB [ "options" ]
.SH DESCRIPTION
.I Tema.simulate 
is used to simulate models without executing them. Tema.simulate tries to 
detect model format automatically from file extension.
.SH ARGUMENTS
.TP
.B filename
Name of the model. If no filename is given or filename is -, reads from 
standard input.
.SH OPTIONS
.B \-h, \--help
Show help message and exit
.TP
.B \-f FORMAT, \--format=FORMAT
Format of the model file. Examples of model formats are lstsmodel, 
mdmmodel, tracelogmodel and parallellstsmodel. Overrides automatic model 
format detection.
.TP
.B \--testdata=TESTDATA
Testdata for model.
.SH EXAMPLES
.TP
.B tema.simulate example.lsts
tema.simulate reads model from file
.B example.lsts.
Model format is detected automatically from file extension.
.TP
.B tema.simulate -f parallellstsmodel - < rules.ext
tema.simulate reads model from standard input and uses model type 
parallellstsmodel. Reading from standard input requires format option -f
.SH SEE ALSO
tema.xsimulate(1)
