.TH TEMA.FILTEREXPAND 1 local
.SH NAME
tema.filterexpand \- Filter test model
.SH SYNOPSIS
.B tema.filterexpand
rulesfile
.RB [ "options" ]
.SH DESCRIPTION
.I Tema.filterexpand
is used to filter test models.
.SH ARGUMENTS
.TP
.B rulesfile
Rules file to filter
.SH OPTIONS
.B Run tema.filterexpand -h for options and examples
.SH SEE ALSO
.IR tema.rextendedrules (1),
.IR tema.testengine (1)

